# Generated by Django 2.0.6 on 2018-06-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(0, '男'), (1, '女')], default='female', max_length=6),
        ),
    ]
