# Generated by Django 2.0.6 on 2018-06-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180607_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='/static/image/default.png', upload_to='image/%Y/%m/%d'),
        ),
    ]
